# Generated by Django 5.1.2 on 2024-10-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
