# Generated by Django 5.1.2 on 2024-10-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_book_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_title", models.CharField(max_length=255)),
                ("author_name", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[("create", "Created"), ("delete", "Deleted")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
